# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in ruby-kybus.gemspec
gemspec
gem "aws-sdk-s3", "~> 1.156"
gem "aws-sdk-sqs", "~> 1.80"
gem "httparty", "~> 0.22.0"
gem "kybus-client", "~> 0.1.0"
gem "kybus-logger", "~> 0.3.0"
gem "minitest", "~> 5.24"
gem "mocha", "~> 2.4"
gem "pry", "~> 0.14.2"
gem "rack-minitest", "~> 0.0.10"
gem "rake", "~> 13.2"
gem "rdoc", "~> 6.7"
gem "sequel", "~> 5.82"
gem "simplecov", "~> 0.22.0"
gem "sqlite3", "~> 2.0"
gem "webmock", "~> 3.23"
