# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in ruby-kybus.gemspec
gemspec

gem 'kybus-logger', '~> 0.1'
gem 'minitest', '~> 5.19'
gem 'mocha', '~> 2.0'
gem 'pry', '~> 0.12'
gem 'rack-minitest', '~> 0.0'
gem 'rake', '~> 12.3'
gem 'rdoc', '~> 6.1'
gem 'simplecov', '~> 0.16'
gem 'webmock', '~> 3.5'
