schema:
  use_plugins:
    - etl_fields
    - soft_delete
  models:
    users:
      fields:
        username:
          type: string
          # alphanumeric:
          #   extra_chars: '._-'
          size: 32
          not_null:
          keys:
            primary: true
        borndate:
          type: string
          not_null:
          # keys:
          #   index: true
        email:
          type: string
          size: 64
          not_null:
          regex: '\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z'
          # index: true
        mobile:
          type: string
          not_null:
          size: 16
          # index: true
      configs: {}
    passwords:
      configs: {}
      fields:
        password:
          type: strong_password
        username:
          type:
            name: foreign_key
            table: users
    auth_plugins:
      configs: {}
      fields:
        auth_source:
          type: auth_source
        username:
          type:
            name: foreign_key
            table: users
        metadata:
          type: json
    wallets:
      configs: {}
      fields:
        wallet_id:
          type: serial
        username:
          type:
            name: foreign_key
            table: users
    transactions:
      configs: {}
      fields:
        source_wallet:
          type:
            name: foreign_key
            optional: true
            table: wallets
            field: wallet_id
        destination_wallet:
          type:
            name: foreign_key
            table: wallets
            field: wallet_id
        amount:
          type:
            name: money
  repositories:
    default:
      name: json
      storage: "storage/$name"
