mode_ci:
  enabled: true # default is false
path: '.' # Set path where report will be saved (tmp/rubycritic by default)
threshold_score: 90 # default is 0
deduplicate_symlinks: true # default is false
suppress_ratings: false # default is false
no_browser: true # default is false
formats: # Available values are: html, json, console, lint. Default value is html.
  - console
minimum_score: 95 # default is 0
