AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - lib/ods.rb
    - vendor/**/*
    - .bundle/**/*
Style/Documentation:
  Enabled: false
Metrics:
  Exclude:
  - lib/bot/core/commands.rb
  - lib/bot/core/roles.rb
  - test/**/*
  - db/**/*
  - bin/**/*
Layout/LineLength:
  Exclude:
    - bin/*
