# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in ruby-kybus.gemspec
gemspec

group :development do
  gem 'kybus-logger', '~> 0.1'
  gem 'kybus-storage', '~> 0.1'
  gem 'minitest', '~> 5.11'
  gem 'mocha', '~> 1.8'
  gem 'pry', '~> 0.12'
  gem 'rack-minitest', '~> 0.0'
  gem 'rake', '~> 12.3'
  gem 'rdoc', '~> 6.1'
  gem 'sequel'
  gem 'sidekiq'
  gem 'simplecov', '~> 0.16'
  gem 'sqlite3'
  gem 'telegram-bot-ruby'
  gem 'webmock', '~> 3.5'
end
