# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in ruby-kybus.gemspec
gemspec

gem 'kybus-core', '~> 0.1'
gem 'minitest', '~> 5.0'
gem 'mocha'
gem 'pry', '~> 0.10'
gem 'rake', '~> 12.0'
gem 'rdoc'
gem 'simplecov'
