# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in ruby-kybus.gemspec
gemspec

gem 'amazing_print', '~> 1.6'
gem 'bcrypt', '~> 3.1'
gem 'minitest', '~> 5.24'
gem 'mocha', '~> 2.4'
gem 'pry', '~> 0.14.2'
gem 'rack-minitest', '~> 0.0.10'
gem 'rake', '~> 13.2'
gem 'rdoc', '~> 6.7'
gem 'rubocop', '~> 1.59'
gem 'rubocop-minitest', '~> 0.34.5'
gem 'rubocop-performance', '~> 1.20'
gem 'rubocop-rake', '~> 0.6.0'
gem 'rubycritic', '~> 4.9'
gem 'simplecov', '~> 0.22.0'
gem 'sqlite3', '~> 1.4'
gem 'webmock', '~> 3.23'
