github:
  user: REPLACE_ME
  pass: REPLACE_ME
  endpoint: REPLACE_ME

sql:
  primary:
    user: REPLACE_ME
    pass: REPLACE_ME
    endpoint: REPLACE_ME
    port: 3306

working_days:
  - monday
  - tuesday
  - wednesday
  - thursday
  - friday

complex_keys:
  hash:
    string: REPLACE
    number: 42
    hash:
      a: b
      c: d
  array:
    - a
    - hash:
        a: b
        c: d
    - array:
      - 1
      - 2
      - 3

missing_keys:
  on_a_hash:
    k: REPLACE_ME
    v: REPLACE_ME
  on_an_array:
    - REPLACE_ME
    - REPLACE_ME
value: REPLACE_ME
