aws:
  default_keys:
    key: AKIA818AD3DLKD
    secret: 91$jsad.123^`aks012jeLa+`
    region: us-east-1
  s3:
    user_record:
      bucket: ant-qa-users
    log_record:
      bucket: logprovider-qa-log
      key: AKIA99812AKDLA1
      secret: OO=A18+$.alsk1jsla1s
      region: eu-west-1
      test_connection:
        list: {}
        put: ant_testing.txt
        get: ant_testing.txt
  sqs:
    etl_pipeline:
      queue: ant-etl_pipeline
      test_connection: true
    mailing:
      queue: ant-mailing
