rest_clients:
  github:
    basic_auth:
      user: Ant
      pass: SecretPassword
    protocol: https
    host: api.github.com
    validator: none
    format: json
  wallet:
    protocol: http
    host: ant-wallet.com
    validate: jsend
    format: json
