# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in ruby-kybus.gemspec
gemspec

gem 'httparty', '~> 0.22.0'
gem 'minitest', '~> 5.24'
gem 'mocha', '~> 2.4'
gem 'pry', '~> 0.14.2'
gem 'rack-minitest', '~> 0.0.10'
gem 'rake', '~> 12.3'
gem 'rdoc', '~> 6.7'
gem 'simplecov', '~> 0.22.0'
gem 'webmock', '~> 3.23'
