name: ci_any_branch
on:
  push:
    branches: "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set ruby version file
        run: echo '3.3.2' > .ruby-version
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: locally install gems
        run: ./local_install.sh
      - name: run tests
        run: ./test.sh
      - name: run rubocop
        run: gem install rubocop && rubocop -c .rubocop.yml
      - name: run rubycritic
        run: gem install rubycritic && rubycritic . --no-browser -s 90
